# This is just for completeness of the Cloud Solutions Documentation.

version: "3"
services:
  spring-boot-admin:
    platform: linux/amd64
    image: ca38c814185cacr.azurecr.io/lakesidemutual-spring-boot-admin:latest
    ports:
      - "9000:9000"

  customer-core:
    platform: linux/amd64
    image: ca38c814185cacr.azurecr.io/lakesidemutual-customer-core:latest
    environment:
      - "SPRING_BOOT_ADMIN_CLIENT_URL=https://spring-boot-admin.greenfield-5544cd00.westus2.azurecontainerapps.io"
    ports:
      - "8110:8110"

  customer-management-backend:
    platform: linux/amd64
    image: ca38c814185cacr.azurecr.io/lakesidemutual-customer-management-backend:latest
    depends_on:
      - customer-core
    environment:
      - "CUSTOMERCORE_BASEURL=https://customer-core.greenfield-5544cd00.westus2.azurecontainerapps.io"
      - "SPRING_BOOT_ADMIN_CLIENT_URL=https://spring-boot-admin.greenfield-5544cd00.westus2.azurecontainerapps.io"
    ports:
      - "8100:8100"

  customer-management-frontend:
    platform: linux/amd64
    image: ca38c814185cacr.azurecr.io/lakesidemutual-customer-management-frontend:latest
    depends_on:
      - customer-management-backend
    environment:
      - "REACT_APP_CUSTOMER_SELF_SERVICE_BACKEND=https://customer-self-service-backend.greenfield-5544cd00.westus2.azurecontainerapps.io"
      - "REACT_APP_CUSTOMER_MANAGEMENT_BACKEND=https://customer-management-backend.greenfield-5544cd00.westus2.azurecontainerapps.io"
      - "REACT_APP_POLICY_MANAGEMENT_FRONTEND=https://policy-management-backend.greenfield-5544cd00.westus2.azurecontainerapps.io"
    ports:
      - "3020:80"

  policy-management-backend:
    platform: linux/amd64
    image: ca38c814185cacr.azurecr.io/lakesidemutual-policy-management-backend:latest
    depends_on:
      - customer-core
    environment:
      - "CUSTOMERCORE_BASEURL=https://customer-core.greenfield-5544cd00.westus2.azurecontainerapps.io"
      - "SPRING_BOOT_ADMIN_CLIENT_URL=https://spring-boot-admin.greenfield-5544cd00.westus2.azurecontainerapps.io"
    ports:
      - "8090:8090"
      - "61613:61613"
      - "61616:61616"

  policy-management-frontend:
    platform: linux/amd64
    image: ca38c814185cacr.azurecr.io/lakesidemutual-policy-management-frontend:latest
    depends_on:
      - policy-management-backend
    environment:
      - "VUE_APP_POLICY_MANAGEMENT_BACKEND=https://policy-management-backend.greenfield-5544cd00.westus2.azurecontainerapps.io"
    ports:
      - "3010:80"

  customer-self-service-backend:
    platform: linux/amd64
    image: ca38c814185cacr.azurecr.io/lakesidemutual-customer-self-service-backend:latest
    depends_on:
      - customer-core
      - policy-management-backend
    environment:
      - "CUSTOMERCORE_BASEURL=https://customer-core.greenfield-5544cd00.westus2.azurecontainerapps.io"
      - "POLICYMANAGEMENT_TCPBROKERBINDADDRESS=tcp://policy-management-backend:61616"
      - "SPRING_BOOT_ADMIN_CLIENT_URL=https://spring-boot-admin.greenfield-5544cd00.westus2.azurecontainerapps.io"
    ports:
      - "8080:8080"

  customer-self-service-frontend:
    platform: linux/amd64
    image: ca38c814185cacr.azurecr.io/lakesidemutual-customer-self-service-frontend:latest
    depends_on:
      - customer-self-service-backend
      - customer-management-backend
      - policy-management-backend
    environment:
      - "REACT_APP_CUSTOMER_SELF_SERVICE_BACKEND=https://customer-self-service-backend.greenfield-5544cd00.westus2.azurecontainerapps.io"
      - "REACT_APP_POLICY_MANAGEMENT_BACKEND=https://policy-management-backend.greenfield-5544cd00.westus2.azurecontainerapps.io"
      - "REACT_APP_CUSTOMER_MANAGEMENT_BACKEND=https://customer-management-backend.greenfield-5544cd00.westus2.azurecontainerapps.io"
    ports:
      - "3000:80"
      
  risk-management-server:
    platform: linux/amd64
    image: ca38c814185cacr.azurecr.io/lakesidemutual-risk-management-server:latest
    depends_on:
      - policy-management-backend
    environment:
      - "ACTIVEMQ_HOST=https://policy-management-backend.greenfield-5544cd00.westus2.azurecontainerapps.io"
      - "ACTIVEMQ_PORT=61613"
    ports:
      - "50051:50051"
